version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Build(deps)"
      
  - package-ecosystem: "nuget"
    directory: "/src/test"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Build(deps)"
      
  - package-ecosystem: "nuget"
    directory: "/docs"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Build(deps)"
