name: ✨ Documentation Improvement Proposal
description: File a documentation improvement proposal
title: "[Docs]: "
labels: ["enhancement"]
assignees:
  - desmondinho
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation improvement proposal!
  - type: dropdown
    id: enhancement-type
    attributes:
      label: Feature request type
      options:
        - Component
        - Component API
        - Other
    validations:
      required: true
  - type: input
    id: component
    attributes:
      label: Component name
      description: If the proposal is related to a component, provide its name.
      placeholder: e.g. LumexButton
  - type: textarea
    id: expectations
    attributes:
      label: What should be done?
      description: Provide a description of your proposal in a straightforward and brief manner.
      placeholder: Hey folks, what if we improved a wording of...
    validations:
      required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Pull Request
      description: Are you interested in implementing the proposal via a Pull Request?
      options:
        - label: I would like to do a Pull Request
