name: Publish LumexUI to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/LumexUI
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Pack NuGet package
      run: dotnet pack -c Release --output nupkgs

    - name: Push to NuGet
      run: dotnet nuget push nupkgs/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
