name: Update Material Icons
on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * 5"
jobs:
  update-icons:
    name: Update Material Icons
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Run Update Script
      working-directory: ./scripts
      run: |
        python update_icons.py
    - name: Commit
      run: |
        git add .
        git diff --staged --quiet || git -c user.name='GitHub Actions Bot' -c user.email='<>' commit -m 'Update Material Icons'
        git push origin main
